"""add attendees_raw to meetings

Revision ID: 45b4fd14ee56
Revises: ca307ff586d1
Create Date: 2026-06-09 11:17:21.610042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45b4fd14ee56'
down_revision: Union[str, None] = 'ca307ff586d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('registered_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upn', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('business_unit_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registered_users_upn'), 'registered_users', ['upn'], unique=True)
    op.add_column('meeting_participants', sa.Column('access_type', sa.String(length=20), server_default='participant', nullable=False))
    op.add_column('meetings', sa.Column('attendees_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'attendees_raw')
    op.drop_column('meeting_participants', 'access_type')
    op.drop_index(op.f('ix_registered_users_upn'), table_name='registered_users')
    op.drop_table('registered_users')
    op.drop_table('business_units')
    # ### end Alembic commands ###
